# Generated by Django 5.2.4 on 2026-02-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('purchase', 'Purchase'), ('download', 'Download')], max_length=20),
        ),
    ]
