# Generated by Django 5.1 on 2026-03-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pesapal_tracking_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
