# Generated by Django 4.2.29 on 2026-06-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_pesapal_tracking_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_gateway', models.CharField(choices=[('pesapal', 'Pesapal'), ('mpesa', 'M-Pesa')], default='pesapal', max_length=20)),
                ('pesapal_consumer_key', models.CharField(blank=True, max_length=255)),
                ('pesapal_consumer_secret', models.CharField(blank=True, max_length=255)),
                ('pesapal_environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('live', 'Live')], default='live', max_length=10)),
                ('pesapal_ipn_id', models.CharField(blank=True, help_text='Register once via shell then paste the returned IPN ID here.', max_length=255)),
                ('mpesa_consumer_key', models.CharField(blank=True, max_length=255)),
                ('mpesa_consumer_secret', models.CharField(blank=True, max_length=255)),
                ('mpesa_shortcode', models.CharField(blank=True, max_length=20)),
                ('mpesa_passkey', models.CharField(blank=True, max_length=255)),
                ('mpesa_environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('live', 'Live')], default='sandbox', max_length=10)),
            ],
            options={
                'verbose_name': 'Payment Settings',
                'verbose_name_plural': 'Payment Settings',
            },
        ),
    ]
