# Generated by Django 4.2.29 on 2026-07-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymentsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='mpesa_checkout_request_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
