# Generated by Django 4.2.29 on 2026-04-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_newspost_newsview'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pastpaper',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
