# Generated by Django 5.2.4 on 2025-07-22 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources','0003_alter_exams_id_alter_news_id_alter_notes_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exams',
            new_name='Exam',
        ),
        migrations.RenameModel(
            old_name='Notes',
            new_name='Note',
        ),
        migrations.RenameModel(
            old_name='PastPapers',
            new_name='PastPaper',
        ),
    ]
